import Link from "next/link"; import {notFound} from "next/navigation";
const pages:Record<string,{title:string;body:React.ReactNode}>={
 about:{title:"About SonnetSkills",body:<><p>SonnetSkills creates practical learning resources for founders, leaders and operators who want to apply technology to real business problems.</p><p>SonnetSkills is a brand of Taucap Private Limited.</p></>},
 contact:{title:"Contact",body:<><p>For product access, billing or support, email <a href="mailto:support@sonnetskills.com">support@sonnetskills.com</a>.</p><p>We aim to respond to support requests within a reasonable business timeframe.</p></>},
 terms:{title:"Terms & Conditions",body:<><p>These terms govern your purchase and use of digital products sold under the SonnetSkills brand by Taucap Private Limited.</p><h2>Digital licence</h2><p>Your purchase grants you a personal, non-transferable licence to access and use the playbook. You may not resell, redistribute or publicly reproduce it.</p><h2>Payment and access</h2><p>Payment is one-time and processed by our payment provider. Access is supplied after verified successful payment. You are responsible for providing accurate contact information.</p><h2>Educational information</h2><p>The playbook provides educational information, not legal, financial or professional advice. Business results depend on implementation and context.</p></>},
 privacy:{title:"Privacy Policy",body:<><p>Taucap Private Limited processes information you provide through SonnetSkills to complete your purchase, deliver access, provide support, prevent fraud and meet legal obligations.</p><h2>Information collected</h2><p>We may collect your name, email, mobile number, payment status, order identifiers, attribution data, device or session identifiers, and consent records. Card or bank credentials are handled by the payment provider and are not stored by us.</p><h2>Marketing</h2><p>Marketing messages are sent only when you provide separate consent. You may withdraw that consent at any time by contacting support.</p><h2>Retention and sharing</h2><p>Information is retained only as reasonably necessary. It may be shared with service providers such as payment, delivery, analytics or hosting providers under appropriate safeguards.</p></>},
 "refund-policy":{title:"Refund & Cancellation Policy",body:<><p>Because this is an instantly delivered digital product, purchases are generally final after successful access is delivered.</p><h2>When a refund may be considered</h2><p>Duplicate charges; a successful payment where access could not be provided and support could not resolve it; or a verified billing or payment error.</p><h2>What is not covered</h2><p>Change of mind, individual expectations, lack of implementation, or business results. Contact support with your order ID for review.</p></>},
 "delivery-policy":{title:"Digital Delivery Policy",body:<><p>This is a digital product; no physical item will be shipped. After verified successful payment, access is shown on the confirmation page and/or sent to the email or mobile number provided at checkout.</p><p>If delivery is delayed, check the contact details you submitted and email support with your order ID.</p></>}
};
export default async function Policy({params}:{params:Promise<{slug:string}>}){const{slug}=await params,p=pages[slug];if(!p)notFound();return <main><header className="container flex h-20 items-center justify-between border-b border-black/15"><Link href="/" className="text-xl font-black">SONNET<span className="text-[#d71914]">SKILLS</span></Link><Link href="/" className="text-sm font-bold">Back to playbook</Link></header><article className="container max-w-3xl py-20"><p className="eyebrow mb-5">Legal & information</p><h1 className="section-title">{p.title}</h1><div className="mt-10 space-y-5 text-lg leading-relaxed text-black/70 [&_h2]:pt-5 [&_h2]:text-2xl [&_h2]:font-black [&_a]:underline">{p.body}</div><p className="mt-14 border-t border-black/15 pt-5 text-sm text-black/50">SonnetSkills is a brand of Taucap Private Limited.<br/>© 2026 Taucap Private Limited. All rights reserved.</p></article></main>}
